Externalise tool API server and import route from dependency instead
I had to update ClojureScript dependency as well since otherwise it
would trigger a transit-java bug due to an older version being pulled:
java.lang.NoSuchMethodError: com.cognitect.transit.TransitFactory.writer